# Generated by Django 5.0.4 on 2024-04-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailmate", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63)),
                ("subject", models.CharField(max_length=63)),
                ("body", models.TextField()),
            ],
        ),
    ]
