# Generated by Django 5.0.4 on 2024-04-10 08:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailmate", "0002_emailtemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="scheduled_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Schedule email to be sent at a future time.",
            ),
        ),
    ]
